### ISSUE TITLE
Abstract away from data-transformers and analysers the need to know about the actual SUT they are applied to

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-analyses-scheduler#61]
We should make the `data-transformers` and the `analysers` unaware of the existence of different SUTs and different versions. They must be just configured with the correct configuration files, determined by the `spark-tasks-sender` that strip out the actual information of the SUT name and version.

It should:
- Rename on submit if possible
- If not possible, handle it in a different way, maybe through a temporary file
- **Even simpler, send the actual file and the filename**

This also impacts https://travis-ci.org/benchflow/data-transformers/builds/143378743 that currently does not build because of the way you reference to the configuration file.

**Comment by Cerfoglg** [comment]
@VincenzoFerme The current solution to this is now sending to the scripts the name of the configuration file (so they can retrieve it via SparkFiles), instead of the SUTName. The analyses scheduler takes care of getting the right file and sending it to the scripts. Also, config files should always have the same name regardless (data-transformers.configuration.yml and analysers.configuration.yml), and they are divided into different folders for different SUTs and versions.

**Comment by VincenzoFerme** [comment]
Fixed in https://github.com/benchflow/data-analyses-scheduler/pull/68
